name: deploy

on:
  workflow_call:

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key for EC2 connection
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to EC2 Instance
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@ec2-13-126-190-26.ap-south-1.compute.amazonaws.com << 'EOF'
          # Navigate to the project directory
          cd auth-docs-service

          # Ensure we're on the correct branch
          git checkout qa
          
          # Fetch the latest changes
          git pull origin qa

          # Install dependencies
          npm install

          # Run migrations (if needed)
          npm run typeorm migration:run -- -d src/common/datasource.ts

          # Build the application
          npm run build

          # Kill the existing PM2 process (if any)
          pm2 delete auth-docs-service || true

          # Start the application with PM2
          pm2 start npm --name "auth-docs-service" -- run start:prod
        EOF
