name: deploy

on:
  workflow_call:

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key for EC2 connection
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: SSH to EC2 and deploy the service
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@ec2-13-126-190-26.ap-south-1.compute.amazonaws.com << 'EOF'
          screen -r

          # Stop the running service
          kill $(ps aux | grep 'npm run start:prod' | awk '{print $1}')

          # Ensure we're on the correct branch
          git checkout qa
          
          # Fetch the latest QA branch
          git pull origin qa

          # Install dependencies
          npm install

          # Run migrations
          npm run typeorm migration:run -- -d src/common/datasource.ts

          # Run build
          npm run build

          # Start the service
          npm run start:prod

          # Detach from the screen
          Ctrl+A D
        EOF
