name: test

on:
  push:
    branches:
      - master
  workflow_call:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Save npm cache
      id: auth-docs-cache
      uses: actions/cache@v4
      with:
        path: node_modules
        key: auth-docs-test-cache-npm-${{ hashFiles('package-lock.json') }}

    - name: npm ci
      if: steps.auth-docs-cache.outputs.cache-hit != 'true'
      run: |
        npm ci

    - name: Copy .env
      run: cp .env.example .env

    - name: Run Unit Tests
      run: npm run test

    - name: Run E2E Tests
      run: npm run test:e2e
